# Generated by Django 3.2.8 on 2024-04-24 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='notes',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.CharField(default='Over 9000!', max_length=100),
        ),
        migrations.AddField(
            model_name='bug',
            name='solution',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Working on Solution', 'Working on Solution'), ('To Revisit', 'To Revisit'), ('Solved', 'Solved')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='technology',
            field=models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('JavaScript (ES9)', 'JavaScript (ES9)'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native'), ('Deployment', 'Deployment'), ('Other', 'Other')], default='Django', max_length=50),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('Git & GitHub', 'Git & GitHub'), ('Heroku', 'Heroku'), ('PostgreSQL', 'PostgreSQL'), ('PowerShell', 'PowerShell'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native'), ('Other', 'Other')], default='Django', max_length=50)),
                ('description', models.CharField(default='Over 9000!', max_length=1000)),
                ('command', models.CharField(default='Over 9000!', max_length=1000)),
                ('type', models.CharField(choices=[('Command', 'Command'), ('Documentation Link', 'Documentation Link')], default='Command', max_length=50)),
                ('notes', models.CharField(default='Over 9000!', max_length=1000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
