# Generated by Django 3.2.8 on 2024-04-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20240424_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='owner',
        ),
    ]
