# Generated by Django 3.2.8 on 2022-03-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220301_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='notes',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('To Revisit', 'To Revisit'), ('Solved', 'Solved')], default='Open', max_length=20),
        ),
    ]
