# Generated by Django 3.2.8 on 2024-04-24 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_remove_command_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='auth.user'),
            preserve_default=False,
        ),
    ]
