# Generated by Django 3.2.8 on 2022-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220428_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='technology',
            field=models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('JavaScript (ES9)', 'JavaScript (ES9)'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native')], default='Django', max_length=50),
        ),
    ]
