# Generated by Django 3.2.8 on 2022-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_bug_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('Git & GitHub', 'Git & GitHub'), ('Heroku', 'Heroku'), ('PostgreSQL', 'PostgreSQL'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native'), ('Other', 'Other')], default='Django', max_length=50)),
                ('description', models.CharField(default='Over 9000!', max_length=100)),
                ('command', models.CharField(default='Over 9000!', max_length=100)),
                ('notes', models.CharField(default='Over 9000!', max_length=1000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bug',
            name='technology',
            field=models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('JavaScript (ES9)', 'JavaScript (ES9)'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native'), ('Deployment', 'Deployment'), ('Other', 'Other')], default='Django', max_length=50),
        ),
    ]
