# Generated by Django 3.2.8 on 2022-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20221001_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='toggle',
            field=models.CharField(choices=[('Command', 'Command'), ('Documentation Link', 'Documentation Link')], default='Command', max_length=50),
        ),
    ]
