# Generated by Django 3.2.8 on 2024-04-24 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_auto_20240424_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='notes',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
        migrations.AddField(
            model_name='command',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='auth.user'),
            preserve_default=False,
        ),
    ]
