# Generated by Django 3.2.8 on 2024-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20240424_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='technology',
            field=models.CharField(choices=[('CLI | Bash', 'CLI | Bash'), ('CLI | Command Prompt', 'CLI | Command Prompt'), ('CLI | PowerShell', 'CLI | PowerShell'), ('CLI | Zsh', 'CLI | Zsh'), ('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('Git | GitHub', 'Git | GitHub'), ('Heroku', 'Heroku'), ('PostgreSQL', 'PostgreSQL'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native'), ('Other', 'Other')], default='CLI | Bash', max_length=50),
        ),
    ]
