# Generated by Django 3.2.8 on 2022-10-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_command_toggle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='toggle',
            new_name='type',
        ),
    ]
