# Generated by Django 3.2.8 on 2023-11-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_toggle_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='technology',
            field=models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('Git & GitHub', 'Git & GitHub'), ('Heroku', 'Heroku'), ('PostgreSQL', 'PostgreSQL'), ('PowerShell', 'PowerShell'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native'), ('Other', 'Other')], default='Django', max_length=50),
        ),
    ]
