# Generated by Django 3.2.8 on 2023-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_command_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
    ]
