# Generated by Django 3.2.8 on 2024-04-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='username',
            field=models.CharField(default='Goken', max_length=50),
            preserve_default=False,
        ),
    ]
