# Generated by Django 3.2.8 on 2024-04-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_command_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='username',
        ),
    ]
