# Generated by Django 3.2.8 on 2022-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220301_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.CharField(default='Over 9000!', max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='solution',
            field=models.CharField(default='Over 9000!', max_length=1000),
        ),
    ]
