# Generated by Django 3.2.8 on 2022-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220315_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Working on Solution', 'Working on Solution'), ('To Revisit', 'To Revisit'), ('Solved', 'Solved')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='technology',
            field=models.CharField(choices=[('Django', 'Django'), ('Django REST Framework', 'Django'), ('JavaScript (ES9)', 'JavaScript (ES9)'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Python 3', 'Python 3'), ('React.js', 'React.js'), ('React Native', 'React Native')], default='Django', max_length=50),
        ),
    ]
